---
!!seq [
  !!str "docker build -t udagram-api-feed ./udagram-api-feed",
  !!str "docker build -t udagram-api-user ./udagram-api-user",
  !!str "docker build -t udagram-frontend ./udagram-frontend",
  !!str "docker build -t udagram-reverseproxy ./udagram-reverseproxy",
  !!str "docker tag udagram-api-feed dunggin/udagram-api-feed:v1",
  !!str "docker tag udagram-api-user dunggin/udagram-api-user:v1",
  !!str "docker tag udagram-frontend dunggin/udagram-frontend:v1",
  !!str "docker tag udagram-reverseproxy dunggin/udagram-reverseproxy:v1",
  !!str "echo \"DOCKER PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin",
  !!str "docker push dunggin/udagram-api-feed:v1",
  !!str "docker push dunggin/udagram-api-user:v1",
  !!str "docker push dunggin/udagram-frontend:v1",
  !!str "docker push dunggin/udagram-reverseproxy:v1",
]