apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-api-user
  name: backend-api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-user

