apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-reverseproxy
  name: udagram-reverseproxy
spec:
  ports:
  - name: "udagram-reverseproxy"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-reverseproxy

